from .MainWindow import Ui_MainWindow
from .MainSettingsWindow import Ui_MainSettingsWindow
from .MainChangeSettingsWindow import Ui_MainChangeSettingsWindow
from .MainPxeWindow import Ui_MainPxeWindow
from .MainRemoteSettingsWindow import Ui_RemoteSettingsWindow