# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'adminka/qt/MainChangeSettingsWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainSettingsWindow(object):
    def setupUi(self, MainSettingsWindow, width=921, height=537):
        MainSettingsWindow.setObjectName("MainSettingsWindow")
        MainSettingsWindow.resize(width, height)
        MainSettingsWindow.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("adminka/qt/../resources/ico/logo.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainSettingsWindow.setWindowIcon(icon)
        MainSettingsWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.centralwidget = QtWidgets.QWidget(MainSettingsWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainSettingsWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainSettingsWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1141, 24))
        self.menubar.setObjectName("menubar")
        self.menu_LocalSettings = QtWidgets.QMenu(self.menubar)
        self.menu_LocalSettings.setObjectName("menu_LocalSettings")
        self.menu_RemoteSettings = QtWidgets.QMenu(self.menubar)
        self.menu_RemoteSettings.setObjectName("menu_RemoteSettings")
        self.menu_NetworkScanner = QtWidgets.QMenu(self.menubar)
        self.menu_NetworkScanner.setObjectName("menu_NetworkScanner")
        MainSettingsWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainSettingsWindow)
        self.statusbar.setObjectName("statusbar")
        MainSettingsWindow.setStatusBar(self.statusbar)
        self.action_Exit = QtWidgets.QAction(MainSettingsWindow)
        self.action_Exit.setObjectName("action_Exit")
        self.action_MainSettings = QtWidgets.QAction(MainSettingsWindow)
        self.action_MainSettings.setObjectName("action_MainSettings")
        self.action_OpenRemoteSettings = QtWidgets.QAction(MainSettingsWindow)
        self.action_OpenRemoteSettings.setObjectName("action_OpenRemoteSettings")
        self.action_ChangeSettings = QtWidgets.QAction(MainSettingsWindow)
        self.action_ChangeSettings.setObjectName("action_ChangeSettings")
        self.action_PXE = QtWidgets.QAction(MainSettingsWindow)
        self.action_PXE.setObjectName("action_PXE")
        self.menu_LocalSettings.addAction(self.action_MainSettings)
        self.menu_LocalSettings.addAction(self.action_ChangeSettings)
        self.menu_LocalSettings.addAction(self.action_PXE)
        self.menu_LocalSettings.addSeparator()
        self.menu_LocalSettings.addAction(self.action_Exit)
        self.menu_RemoteSettings.addAction(self.action_OpenRemoteSettings)
        self.menubar.addAction(self.menu_LocalSettings.menuAction())
        self.menubar.addAction(self.menu_RemoteSettings.menuAction())
        self.menubar.addAction(self.menu_NetworkScanner.menuAction())

        self.retranslateUi(MainSettingsWindow)
        QtCore.QMetaObject.connectSlotsByName(MainSettingsWindow)

    def retranslateUi(self, MainSettingsWindow):
        _translate = QtCore.QCoreApplication.translate
        MainSettingsWindow.setWindowTitle(_translate("MainSettingsWindow", "Настройщик ОС Linux"))
        MainSettingsWindow.setStatusTip(_translate("MainSettingsWindow", "Главное окно программы"))
        self.menu_LocalSettings.setTitle(_translate("MainSettingsWindow", "Локальная настройка"))
        self.menu_RemoteSettings.setTitle(_translate("MainSettingsWindow", "Удалённая настройка"))
        self.menu_NetworkScanner.setTitle(_translate("MainSettingsWindow", "Сканер сети"))
        self.action_Exit.setText(_translate("MainSettingsWindow", "Выход"))
        self.action_Exit.setStatusTip(_translate("MainSettingsWindow", "Выход из программы"))
        self.action_MainSettings.setText(_translate("MainSettingsWindow", "Основные параметры"))
        self.action_MainSettings.setStatusTip(_translate("MainSettingsWindow", "Включает в себя настройку основных (общих) параметров системы"))
        self.action_OpenRemoteSettings.setText(_translate("MainSettingsWindow", "Открыть"))
        self.action_OpenRemoteSettings.setStatusTip(_translate("MainSettingsWindow", "Настройка удаленных машин"))
        self.action_ChangeSettings.setText(_translate("MainSettingsWindow", "Настраиваемые параметры ОС"))
        self.action_ChangeSettings.setStatusTip(_translate("MainSettingsWindow", "Включает в себя настройку индивидуальных параметров системы таких как имя компьютера, сетевые настройки и т.д."))
        self.action_PXE.setText(_translate("MainSettingsWindow", "Настройка PXE сервера"))
        self.action_PXE.setStatusTip(_translate("MainSettingsWindow", "Установка и настройка PXE сервера"))
