# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow, width=809, height=441):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(width, height)
        MainWindow.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../resources/ico/logo.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 805, 24))
        self.menubar.setObjectName("menubar")
        self.menu_LocalSettings = QtWidgets.QMenu(self.menubar)
        self.menu_LocalSettings.setStatusTip("")
        self.menu_LocalSettings.setObjectName("menu_LocalSettings")
        self.menu_RemoteSettings = QtWidgets.QMenu(self.menubar)
        self.menu_RemoteSettings.setObjectName("menu_RemoteSettings")
        self.menu_NetworkScanner = QtWidgets.QMenu(self.menubar)
        self.menu_NetworkScanner.setObjectName("menu_NetworkScanner")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_Exit = QtWidgets.QAction(MainWindow)
        self.action_Exit.setObjectName("action_Exit")
        self.action_MainSettings = QtWidgets.QAction(MainWindow)
        self.action_MainSettings.setObjectName("action_MainSettings")
        self.action_OpenRemoteSettings = QtWidgets.QAction(MainWindow)
        self.action_OpenRemoteSettings.setObjectName("action_OpenRemoteSettings")
        self.menu_LocalSettings.addAction(self.action_MainSettings)
        self.menu_LocalSettings.addSeparator()
        self.menu_LocalSettings.addAction(self.action_Exit)
        self.menu_RemoteSettings.addAction(self.action_OpenRemoteSettings)
        self.menubar.addAction(self.menu_LocalSettings.menuAction())
        self.menubar.addAction(self.menu_RemoteSettings.menuAction())
        self.menubar.addAction(self.menu_NetworkScanner.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Настройщик ОС Linux"))
        self.centralwidget.setStatusTip(_translate("MainWindow", "Основное окно программы"))
        self.menu_LocalSettings.setTitle(_translate("MainWindow", "Локальная настройка"))
        self.menu_RemoteSettings.setTitle(_translate("MainWindow", "Удалённая настройка"))
        self.menu_NetworkScanner.setTitle(_translate("MainWindow", "Сканер сети"))
        self.action_Exit.setText(_translate("MainWindow", "Выход"))
        self.action_Exit.setStatusTip(_translate("MainWindow", "Выход из программы"))
        self.action_MainSettings.setText(_translate("MainWindow", "Основные параметры"))
        self.action_MainSettings.setStatusTip(_translate("MainWindow", "Изменений основных настроек ОС. Установка и удаление программ"))
        self.action_OpenRemoteSettings.setText(_translate("MainWindow", "Открыть"))
        self.action_OpenRemoteSettings.setStatusTip(_translate("MainWindow", "Настройка удаленных машин"))
